### ISSUE TITLE
dataloader_args

### ISSUE THREAD

**Issue by ggabernet** [kipoi/kipoi-veff#34]
Hi,

I am trying to test the kipoi-veff cli taking by example the command in the Kipoi paper, but I get an error:

```
Traceback (most recent call last):
  File "/Users/gisela/anaconda3/envs/kipoi-veff/bin/kipoi", line 10, in <module>
    sys.exit(main())
  File "/Users/gisela/anaconda3/envs/kipoi-veff/lib/python3.6/site-packages/kipoi/__main__.py", line 104, in main
    command_fn(args.command, sys.argv[2:])
  File "/Users/gisela/anaconda3/envs/kipoi-veff/lib/python3.6/site-packages/kipoi_veff/__main__.py", line 11, in cli_main
    kipoi_veff.cli.cli_main(command, raw_args)
  File "/Users/gisela/anaconda3/envs/kipoi-veff/lib/python3.6/site-packages/kipoi_veff/cli.py", line 458, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/Users/gisela/anaconda3/envs/kipoi-veff/lib/python3.6/site-packages/kipoi_veff/cli.py", line 180, in cli_score_variants
    dataloader_arguments = parse_json_file_str_or_arglist(args.dataloader_args)
  File "/Users/gisela/anaconda3/envs/kipoi-veff/lib/python3.6/site-packages/kipoi_utils/utils.py", line 282, in parse_json_file_str_or_arglist
    raise RuntimeError("wrong usage, dataloader_args must be a list")
RuntimeError: wrong usage, dataloader_args must be a list
```

My command:
```
kipoi veff score_variants DeepSEA --dataloader_args '{"fasta_file": "~/.vep/homo_sapiens/97_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa"}' -i 'input.vcf' -o 'output.vcf'
```

I've also tested:
```
kipoi veff score_variants DeepSEA --dataloader_args='{"fasta_file": "~/.vep/homo_sapiens/97_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa"}' -i 'input.vcf' -o 'output.vcf'
```

to no avail.

**Comment by ggabernet** [comment]
turned out to be an old version of kipoi

**Comment by Avsecz** [comment]
Glad that fixed it:)
